language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  - perlbrew -f install-cpanm
  - cpanm -n Devel::Cover::Report::Coveralls
script: perl Build.PL && ./Build && ./Build testcover
after_success:
  - cover -report coveralls

